"""baseline

Revision ID: 02e36ff89761
Revises: 
Create Date: 2026-08-31 21:12:41.173644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02e36ff89761'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_valid', sa.Integer(), nullable=False),
    sa.Column('is_radio', sa.Integer(), nullable=False),
    sa.Column('quality_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('speed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sources', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tvg_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clean_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_results_session_id'), 'channel_results', ['session_id'], unique=False)
    op.create_index('ix_cr_session_group', 'channel_results', ['session_id', 'channel_group'], unique=False)
    op.create_index('ix_cr_session_name', 'channel_results', ['session_id', 'name'], unique=False)
    op.create_index('ix_cr_session_radio', 'channel_results', ['session_id', 'is_radio'], unique=False)
    op.create_index('ix_cr_session_valid', 'channel_results', ['session_id', 'is_valid'], unique=False)
    op.create_index('ix_cr_session_valid_name', 'channel_results', ['session_id', 'is_valid', 'name'], unique=False)
    op.create_index('ix_cr_session_valid_radio', 'channel_results', ['session_id', 'is_valid', 'is_radio'], unique=False)
    op.create_table('channels',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sources', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_channels_group'), 'channels', ['group'], unique=False)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=False)
    op.create_index(op.f('ix_channels_url_key'), 'channels', ['url_key'], unique=False)
    op.create_table('check_events',
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_events_created_at'), 'check_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_check_events_event_type'), 'check_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_check_events_session_id'), 'check_events', ['session_id'], unique=False)
    op.create_index('ix_events_session_type', 'check_events', ['session_id', 'event_type'], unique=False)
    op.create_table('check_history',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_history_created_at'), 'check_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_check_history_session_id'), 'check_history', ['session_id'], unique=False)
    op.create_table('favorite_folders',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fetched_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tvg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tvg_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_radio', sa.Integer(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fc_source_id', 'fetched_channels', ['source_id'], unique=False)
    op.create_index('ix_fc_url_key', 'fetched_channels', ['url_key'], unique=False)
    op.create_index(op.f('ix_fetched_channels_url_key'), 'fetched_channels', ['url_key'], unique=False)
    op.create_table('online_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('protocol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('features', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mirror_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disabled', sa.Integer(), nullable=False),
    sa.Column('epg_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('update_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quality_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cache_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_online_sources_category'), 'online_sources', ['category'], unique=False)
    op.create_index('ix_os_category', 'online_sources', ['category'], unique=False)
    op.create_index('ix_os_protocol', 'online_sources', ['protocol'], unique=False)
    op.create_table('session_summaries',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('likely_valid_count', sa.Integer(), nullable=False),
    sa.Column('tv_count', sa.Integer(), nullable=False),
    sa.Column('radio_count', sa.Integer(), nullable=False),
    sa.Column('avg_latency', sa.Float(), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('check_results',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('quality_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('speed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_results_channel_checked', 'check_results', ['channel_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_check_results_channel_id'), 'check_results', ['channel_id'], unique=False)
    op.create_index(op.f('ix_check_results_checked_at'), 'check_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_check_results_is_valid'), 'check_results', ['is_valid'], unique=False)
    op.create_index(op.f('ix_check_results_quality_tier'), 'check_results', ['quality_tier'], unique=False)
    op.create_index(op.f('ix_check_results_tag'), 'check_results', ['tag'], unique=False)
    op.create_table('custom_channels',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['favorite_folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_custom_channels_folder_id'), 'custom_channels', ['folder_id'], unique=False)
    op.create_table('favorites',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_cn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('channel_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('latency_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['favorite_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_channel_id'), 'favorites', ['channel_id'], unique=False)
    op.create_index(op.f('ix_favorites_folder_id'), 'favorites', ['folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_folder_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_channel_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_custom_channels_folder_id'), table_name='custom_channels')
    op.drop_table('custom_channels')
    op.drop_index(op.f('ix_check_results_tag'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_quality_tier'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_is_valid'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_checked_at'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_channel_id'), table_name='check_results')
    op.drop_index('ix_check_results_channel_checked', table_name='check_results')
    op.drop_table('check_results')
    op.drop_table('session_summaries')
    op.drop_index('ix_os_protocol', table_name='online_sources')
    op.drop_index('ix_os_category', table_name='online_sources')
    op.drop_index(op.f('ix_online_sources_category'), table_name='online_sources')
    op.drop_table('online_sources')
    op.drop_index(op.f('ix_fetched_channels_url_key'), table_name='fetched_channels')
    op.drop_index('ix_fc_url_key', table_name='fetched_channels')
    op.drop_index('ix_fc_source_id', table_name='fetched_channels')
    op.drop_table('fetched_channels')
    op.drop_table('favorite_folders')
    op.drop_index(op.f('ix_check_history_session_id'), table_name='check_history')
    op.drop_index(op.f('ix_check_history_created_at'), table_name='check_history')
    op.drop_table('check_history')
    op.drop_index('ix_events_session_type', table_name='check_events')
    op.drop_index(op.f('ix_check_events_session_id'), table_name='check_events')
    op.drop_index(op.f('ix_check_events_event_type'), table_name='check_events')
    op.drop_index(op.f('ix_check_events_created_at'), table_name='check_events')
    op.drop_table('check_events')
    op.drop_index(op.f('ix_channels_url_key'), table_name='channels')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_group'), table_name='channels')
    op.drop_table('channels')
    op.drop_index('ix_cr_session_valid_radio', table_name='channel_results')
    op.drop_index('ix_cr_session_valid_name', table_name='channel_results')
    op.drop_index('ix_cr_session_valid', table_name='channel_results')
    op.drop_index('ix_cr_session_radio', table_name='channel_results')
    op.drop_index('ix_cr_session_name', table_name='channel_results')
    op.drop_index('ix_cr_session_group', table_name='channel_results')
    op.drop_index(op.f('ix_channel_results_session_id'), table_name='channel_results')
    op.drop_table('channel_results')
    # ### end Alembic commands ###
